# https://taskfile.dev
version: '3'

tasks:
  templates:
    cmds:
      - go tool templ generate

  check:
    cmds:
      - gofmt -d -e -s .
      - go vet ./...
      - go tool staticcheck ./...
      - go tool gosec -quiet ./...
      - go tool golangci-lint run
      - go tool govulncheck
      - go test -race ./...
      - go tool revive
      - go mod tidy

  tools:
    cmds:
      - go get -tool github.com/a-h/templ/cmd/templ
      - go get -tool github.com/amacneil/dbmate
      - go get -tool github.com/golangci/golangci-lint/v2/cmd/golangci-lint
      - go get -tool github.com/securego/gosec/v2/cmd/gosec
      - go get -tool golang.org/x/vuln/cmd/govulncheck
      - go get -tool honnef.co/go/tools/cmd/staticcheck

  test:
    cmds:
      - go test -v -cover -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out