name: Push action
on: push
jobs:
  checks:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/work/go
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Install additional dependencies
        run: sh ./ci-deps.sh
      - name: Run git hooks
        run: ./.githooks/pre-commit